--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/root/.local/share/bg.jpg"

-- Special
background="#0f1913"
foreground="#d7dcd5"
cursor="#d7dcd5"

-- Colors
color0="#0f1913"
color1="#4B8871"
color2="#A59948"
color3="#2F7787"
color4="#269897"
color5="#5E9B9C"
color6="#67BDD0"
color7="#d7dcd5"
color8="#969a95"
color9="#4B8871"
color10="#A59948"
color11="#2F7787"
color12="#269897"
color13="#5E9B9C"
color14="#67BDD0"
color15="#d7dcd5"
