# Shell variables
# Generated by 'wal'
wallpaper='/root/.local/share/bg.jpg'

# Special
background='#0f1913'
foreground='#d7dcd5'
cursor='#d7dcd5'

# Colors
color0='#0f1913'
color1='#4B8871'
color2='#A59948'
color3='#2F7787'
color4='#269897'
color5='#5E9B9C'
color6='#67BDD0'
color7='#d7dcd5'
color8='#969a95'
color9='#4B8871'
color10='#A59948'
color11='#2F7787'
color12='#269897'
color13='#5E9B9C'
color14='#67BDD0'
color15='#d7dcd5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
