;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;==========================================================

[colors]
background = ${xrdb:background:#222}
foreground = ${xrdb:color7:#222}
foreground-alt = ${xrdb:color7:#222}
primary = ${xrdb:color1:#222}
secondary = ${xrdb:color2:#222}
alert = ${xrdb:color3:#222}
disabled = #707880

[bar/example]
width = 100%
height = 18pt
radius = 0

; dpi = 96

background = ${colors.secondary}
foreground = ${colors.foreground}

line-size = 0

; border-size = 0
; border-color = #00000000

padding-left = 0
padding-right = 0

module-margin = 0

; separator = |
; separator-foreground = ${colors.disabled}

font-0 = JetBrains Mono:size=12:antialias=true;2
font-1 = joypixels:pixelsize=12:antialias=true:autohint=true
font-2 = Font Awesome:pixelsize=11:antialias=true:autohint=true;1

modules-left = i3 xwindow
; modules-center = xwindow
modules-right = cpu memory filesystem date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = false

; tray-position = right
fixed-center = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
strip-wsnumbers = true
fuzzy-match = true

; Only show workspaces on the same output as the bar
pin-workspaces = true

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;

label-mode = %mode%
label-mode-padding = 0
label-mode-background = ${colors.background}

; focused = Active workspace on focused monitor
label-focused = %icon%
label-focused-background = ${colors.secondary}
; label-focused-underline  = ${colors.secondary}
label-focused-padding = 1

; unfocused = Inactive workspace on any monitor
label-unfocused = %icon%
label-unfocused-background = ${colors.background}
label-unfocused-padding = 1

; urgent = Workspace with urgency hint set
label-urgent = %icon%
label-urgent-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
format-foreground = ${colors.foreground}
format-padding = 2

[module/filesystem]
type = internal/fs
interval = 30

mount-0 = /
label-mounted = [  %used%/%total% ]
format-mounted-prefix = " "
format-mounted-background = ${colors.background}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
; format-prefix-foreground = ${colors.foreground-alt}
; format-underline = #4bffdc
; format-overline = #4bffdc
label = [  %gb_used%/%gb_free% ]
format-background = ${colors.background}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
; format-prefix-foreground = ${colors.primary}
label = [  %percentage:2%% ]
format-background = ${colors.background}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 5

date = "%a %d %b%"
time = %I:%M %p

format-prefix = " "
; format-prefix-foreground = ${colors.foreground-alt}
; format-underline = #0a6cf5

label = [  %date% ] [  %time% ]
format-background = ${colors.background}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
